@startuml
top to bottom direction

[*] --> INIT

state INIT {
    init_run: Do initialization tasks
}

INIT --> IDLE : Successful initialization

state IDLE {
    idle_entry: Start idle timer
    idle_entry --> idle_run
    idle_run: Wait for events
}

IDLE --> BATTERY : Battery Timer Event (every 60 seconds)

state BATTERY {
    battery_entry: Prepare ADC
    battery_entry --> battery_run
    battery_run: Measure battery and update LED
    battery_run --> IDLE : Return to idle
}

@enduml
