@startuml
top to bottom direction

[*] --> INIT

state INIT {
    init_run: Do initialization tasks
}

INIT --> IDLE : Successful initialization
INIT --> ERROR : ADC/LED init failure

state IDLE {
    idle_entry: Start idle timer  
    idle_entry --> idle_run
    idle_run: Wait for events  
}

IDLE --> BATTERY : Battery Timer Event (every 60 seconds)
IDLE --> MEASURE : Measure Button Pressed
IDLE --> ERROR : Any error detected

state BATTERY {
    battery_entry: Prepare ADC  
    battery_entry --> battery_run  
    battery_run: Measure battery and update LED  
}
BATTERY --> IDLE : Return to idle
BATTERY --> ERROR : ADC error

state MEASURE {
    measure_entry: Setup ECG and temp sensors  
    measure_entry --> measure_run  
    measure_run: Compute BPM and temperature  
}
MEASURE --> IDLE : Return to idle
MEASURE --> ERROR : ADC/temp/error event

state ERROR {
    error_entry: Disable timers & PWM, activate error flags
    error_entry --> error_run
    error_run: Wait for reset button
}
ERROR --> INIT : Reset button pressed

@enduml
